print()
print('Clínica Médica Dra Ivone.')
print()
print()
print()
print('(1) Oftalmologista')
print('(2) Cardiologista')
print('(3) Pediatra')
print()
x = int(input('Digite o número da especialidade escolhida: '))
if (x == 1):
    print()
    print()
    print('A especialidade escolhida foi Oftalmologista!')
    print()
    print('(1)Segunda  (2)Terça  (3)Quarta  (4)Quinta')
    print('      (5)Sexta  (6)Sábado  (7)Domingo')
    print()
    x = int(input('Digite o número do dia em que deseja ser atendido: '))
    if (x == 1):
        print()
        print('Especialidade Oftalmologista, Dia Segunda.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Oftalmologista, Dia Segunda, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e a Dra Ana.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Oftalmologista, Dia Segunda, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e a Dra Ana.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Oftalmologista, Dia Segunda, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro.')
            print()
    elif (x == 2):
        print()
        print('Especialidade Oftalmologista, Dia Terça.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Oftalmologista, Dia Terça, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas e a Dra Ana.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Oftalmologista, Dia Terça, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas e a Dra Ana.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Oftalmologista, Dia Terça, turno Noite.')
            print()
            print()
            print('No horario escolido, Não tem Médico disponivel.')
            print()
    elif (x == 3):
        print()
        print('Especialidade Oftalmologista, Dia Quarta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Oftalmologista, Dia Quarta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e a Dra Ana.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Oftalmologista, Dia Quarta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e a Dra Ana.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Oftalmologista, Dia Quarta, turno Noite.')
            print()
            print()
            print('No horario escolido, Não tem Médico disponivel.')
            print()
    elif (x == 4):
        print()
        print('Especialidade Oftalmologista, Dia Quinta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Oftalmologista, Dia Quinta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas e a Dra Ana.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Oftalmologista, Dia Quinta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas e a Dra Ana.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Oftalmologista, Dia Quinta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas.')
            print()
    elif (x == 5):
        print()
        print('Especialidade Oftalmologista, Dia Sexta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Oftalmologista, Dia Sexta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e a Dra Ana.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Oftalmologista, Dia Sexta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Lucas e a Dra Ana.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Oftalmologista, Dia Sexta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Mauro e Dr Lucas.')
            print()
    elif (x == 6):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()
    elif (x == 7):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()
elif (x == 2):  
    print()
    print()
    print('A especialidade escolhida foi Cardiologista!')
    print()
    print('(1)Segunda  (2)Terça  (3)Quarta  (4)Quinta')
    print('      (5)Sexta  (6)Sábado  (7)Domingo')
    print()
    x = int(input('Digite o número do dia em que deseja ser atendido: '))
    if (x == 1):
        print()
        print('Especialidade Cardiologista, Dia Segunda.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Cardiologista, Dia Segunda, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio e a Dra Carla.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Cardiologista, Dia Segunda, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Carla.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Cardiologista, Dia Segunda, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio e a Dra Carla.')
            print()
    elif (x == 2):
        print()
        print('Especialidade Cardiologista, Dia Terça.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Cardiologista, Dia Terça, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio e a Dra Carla.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Cardiologista, Dia Terça, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Carla.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Cardiologista, Dia Terça, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio e a Dra Carla.')
            print()
    elif (x == 3):
        print()
        print('Especialidade Cardiologista, Dia Quarta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Cardiologista, Dia Quarta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Cardiologista, Dia Quarta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Cláudio e a Dra Rita.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Cardiologista, Dia Quarta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
    elif (x == 4):
        print()
        print('Especialidade Cardiologista, Dia Quinta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Cardiologista, Dia Quinta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Cardiologista, Dia Quinta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Cardiologista, Dia Quinta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
    elif (x == 5):
        print()
        print('Especialidade Cardiologista, Dia Sexta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Cardiologista, Dia Sexta, turno Manhã.')
            print()
            print()
            print('No horario escolido, Não tem Médico disponivel')
            print()
        elif (x == 2):
            print()
            print('Especialidade Cardiologista, Dia Sexta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Cardiologista, Dia Sexta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Rita.')
            print()
    elif (x == 6):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()
    elif (x == 7):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()          
elif (x == 3): 
    print()
    print()
    print('A especialidade escolhida foi Pediatra!')
    print()
    print('(1)Segunda  (2)Terça  (3)Quarta  (4)Quinta')
    print('      (5)Sexta  (6)Sábado  (7)Domingo')
    print()
    x = int(input('Digite o número do dia em que deseja ser atendido: '))
    if (x == 1):
        print()
        print('Especialidade Pediatra, Dia Segunda.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Pediatra, Dia Segunda, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Antônio e a Dra Elis.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Pediatra, Dia Segunda, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Antônio, Dra Alice e a Dra Elis.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Pediatra, Dia Segunda, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Alice e a Dra Elis.')
            print()
    elif (x == 2):
        print()
        print('Especialidade Pediatra, Dia Terça.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Pediatra, Dia Terça, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Ruan e o Dr Antônio.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Pediatra, Dia Terça, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Ruan e o Dr Antônio.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Pediatra, Dia Terça, turno Noite.')
            print()
            print()
            print('No horario escolido, Não tem Médico disponivel')
            print()
    elif (x == 3):
        print()
        print('Especialidade Pediatra, Dia Quarta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Pediatra, Dia Quarta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Antônio.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Pediatra, Dia Quarta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Antônio e a Dra Alice.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Pediatra, Dia Quarta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Alice.')
            print()
    elif (x == 4):  
        print()
        print('Especialidade Pediatra, Dia Quinta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Pediatra, Dia Quinta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Ruan.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Pediatra, Dia Quinta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo o Dr Ruan.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Pediatra, Dia Quinta, turno Noite.')
            print()
            print()
            print('No horario escolido, Não tem Médico disponivel.')
            print()
    elif (x == 5):     
        print()
        print('Especialidade Pediatra, Dia Sexta.')
        print()
        print()
        print('(1)Manhã  (2)Tarde  (3)Noite')
        print()
        x = int(input('Digite o número do turno em que deseja ser atendido: '))
        if (x == 1):
            print()
            print('Especialidade Pediatra, Dia Sexta, turno Manhã.')
            print()
            print()
            print('No horario escolido estara atendendo Dr Ruan e a Dra Elis.')
            print()
        elif (x == 2):
            print()
            print('Especialidade Pediatra, Dia Sexta, turno Tarde.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Alice, a Dra Elis e o Dr Ruan.')
            print()
        elif (x == 3):
            print()
            print('Especialidade Pediatra, Dia Sexta, turno Noite.')
            print()
            print()
            print('No horario escolido estara atendendo a Dra Alice e a Dra Elis.')
            print()
    elif (x == 6):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()
    elif (x == 7):
        print()
        print()
        print('A Clinica não tem Médico disponivel nesse dia!')
        print()
